name: Deploy Hexo Blog

on:
  push:
    branches:
      - main  # Replace 'main' with your Hexo blog's main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'  # Replace with the appropriate Node.js version for your Hexo setup

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npx hexo generate  # Use "npx hexo generate" instead of "npm run generate"

    - name: Deploy
      run: |
        git config --global user.name "jiuyetx"
        git config --global user.email "meteor209@gmail.com"
        npx hexo deploy  # Use "npx hexo deploy" instead of "hexo deploy"
