name: deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install and Build 🔧
        run: |
          npm install -g hexo-cli
          npm install
          hexo clean
          hexo generate

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          FOLDER: public
